apiVersion: cninf-oss.oss.fjj.com/v1alpha1
kind: ObjStore
metadata:
  labels:
    app.kubernetes.io/name: objstore
    app.kubernetes.io/instance: objstore-sample
    app.kubernetes.io/part-of: oss-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oss-operator
  name: objstore-sample
spec:
  # TODO(user): Add fields here
